config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  resources :messages do
    member do
      match :reply, via: %i(get patch)
    end
  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/users/registration_notification_mailer.rb
module Users
  module RegistrationNotificationMailer
    include ActiveSupport::Concern

    def self.included(base)
      base.class_eval do
        after_create :send_admin_mail
      end
    end

    def send_admin_mail
      UserNotificationMailer.send_new_user_message(self).deliver
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Users::RegistrationNotificationMailer

  has_many :messages
  has_one :account, inverse_of: :user

  accepts_nested_attributes_for :account

  def is_admin?
    is_admin
  end

  def full_name
    [first_name, last_name].compact.collect(&:capitalize).join(' ').strip
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :list_of_messages
  private
    def list_of_messages
      @messages =
        if current_user.present? && current_user.is_admin?
          Message.where(reply: [nil, ''])
        elsif current_user.present?
          Message.where(user: current_user)
        else
          Message.all
        end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i(show destroy update)
  before_action :set_messages, only: %i(index reply)
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params.merge(user: current_user))
    respond_with({}) do |format|
      if @message.save
        UserNotificationMailer.sent_to_requester(@message).deliver
        UserNotificationMailer.send_request_to_support(@message).deliver
        format.html do
          redirect_to messages_path, notice: 'Request was created!'
        end
      else
        format.html { render :new }
      end
    end
  end

  def reply
    @message = Message.find(params['id'])
    @message.reply = params[:message][:reply] if params[:message]
    if params[:message]
      if @message.save
        UserNotificationMailer.reply_from_support(@message).deliver
        render action: :index
      end
    else
      render :reply
    end
  end

  def update
    if @message.update(message_params)
      render action: :show
    else
      render :edit
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html do
        flash[:success] =
        redirect_to root_path, notice: 'Message successfully destroyed.'
      end
    end
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:id, :title, :text, :reply)
    end

    def set_messages
      @messages ||= Message.all
    end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters, if: :devise_controller?

    def update_resource(resource, params)
      # resource.build_account
      resource.update_with_password(params)
    end

    protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, account_attributes: [:id, :balance, :currency]])
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_type(type)
    case type.to_sym
    when :alert
      'warning'
    when :error
      'danger'
    when :notice
      'info'
    when :success
      'success'
    else
      type.to_s
    end
  end
end

app/views/landing/index.html.erb
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <%= render partial: 'messages/list_request', locals: { messages: @messages } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleAppTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'shared/navigation' %>
  <%= render partial: 'shared/errors_msg' %>
  <main role="main">
    <%= yield %>
  </main>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="panel-body">
  <h3>Create request to Support</h3>
  <%= form_for @message, url: messages_path,  html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <div class="form-group field" >
      <%= f.label :title, 'Title request', class: 'form-label'  %>
      <%= f.text_field :title, class: 'form-control'  %>
    </div>
    <div class="form-group field" >
      <%= f.label :text, 'Full description', class: 'form-label'  %>
      <%= f.text_area :text, class: 'form-control', cols: 40, rows: 10  %>
    </div>
    <div class="form-group field" >
      <%== f.submit 'Create request', class: 'form-control btn btn-primary submit-button' %>
    </div>
  <%- end %>
</div>

app/views/messages/_list_request.html.erb
<%-if messages.count > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th scope="col">
          Title
        </th>
        <th scope="col">
          Message
        </th>
        <th scope="col">
          User
        </th>
        <th scope="col">
          Time request
        </th>
        <%-if current_user.present? && current_user.is_admin? %>
          <th scope="col">
            Action
          </th>
        <%-end %>
      </tr>
    </thead>
    <tbody>
      <%-if messages.count > 0 %>
        <%- messages.each do |message| %>
          <tr>
            <th scope="row"><%=message.id %></th>
            <td><%=message.title %></td>
            <td><%=message.text %></td>
            <td><%=message.user.full_name.blank? ? message.user.email : message.user.full_name%></td>
            <td><%=message.created_at.strftime('%F %T') %></td>
            <%-if current_user.present? && current_user.is_admin? %>
              <td>
                <%= link_to 'Reply', reply_message_path(message), class: 'btn btn-success' %>
                <%= link_to 'Delete', message_path(message), method: :delete, class: 'btn btn-danger' %>
              </td>
            <%-else %>
              <td><%=message&.reply %></td>
            <%-end %>
          </tr>
        <%-end %>
      <%-end %>
    </tbody>
  </table>
<%- end %>

app/views/messages/_reply_form.html.erb
<div class="panel-body">
  <h3>Answer for a Question</h3>
  <%= form_for @message, url: reply_message_path(@message),  html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <div class="form-group field" >
      <%= f.text_area :reply, class: 'form-control', cols: 40, rows: 10, required: true, autofocus: true, placeholder: "Reply"  %>
    </div>
    <div class="form-group field" >
      <%== f.submit 'Reply', class: 'form-control btn btn-primary submit-button' %>
    </div>
  <%- end %>
</div>

app/views/messages/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%-if current_user.present? && !current_user.is_admin? %>
      <%= link_to 'Create new request to support', new_message_path, class: 'btn btn-info' %>
    <%-end %>
    <%-if current_user&.is_admin? && @messages.count <= 0%>
      <h3>You do not have any request!</h3>
    <%-end %>
    <%= render partial: 'messages/list_request', locals: { messages: @messages } %>
  </div>
</div>

app/views/messages/new.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render partial: 'messages/form' %>
  </div>
</div>

app/views/messages/reply.html.erb
<h3><%= @message&.title %></h3>
<div><%= @message&.text %></div>
<%= render partial: 'messages/reply_form', locals: {message: @message } %>

app/views/messages/show.html.erb
<span>Title Question:</span>
<h3><%= @message&.title %></h3>
<span>Message:</span>
<div><%= @message&.text %></div>
<span>Reply:</span>
<div><%= @message&.reply %></div>

app/views/shared/_errors_msg.html.erb
<div class="info-block">
  <%- flash.each do |type, message| %>
    <div class="row flash-message">
      <div class="col-md-12">
        <div class=<%="alert alert-#{alert_type(type)} alert-dismissible fade in"  %>, role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <div>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%- flash.clear %>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-dark bg-primary navbar-expand-md fixed-top">
  <%= link_to Rails.configuration.application_name, root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=link_to 'Messages', messages_path, class: "nav-link" %>
      </li>
    </ul>
    <div class="pull-right">
      <ul class="navbar-nav">
        <%- if user_signed_in? %>
          <li>
            <%= link_to current_user.full_name.empty? ? current_user.email : current_user.full_name, edit_user_registration_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <%- else %>
          <li>
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <%- end %>
      </ul>
    </div>
  </div>
</nav>